export enum EstoqueOrigem {
  COMPRA = 'COMPRA',
  VENDA = 'VENDA',
  DEVOLUCAO = 'DEVOLUCAO',
  INVENTARIO = 'INVENTARIO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  PRODUCAO = 'PRODUCAO',
  MANUAL = 'MANUAL',
}
